// Render.com Deployment Service
// Ermöglicht das Deployment von Apps zu Render mit automatischem Blueprint

export interface RenderCredentials {
  apiKey: string  // Render API Key (rnd_...)
}

export interface RenderDeploymentConfig {
  projectName: string
  projectType: "nextjs" | "node" | "static" | "docker"
  region: "oregon" | "frankfurt" | "singapore" | "ohio"
  plan: "free" | "starter" | "standard" | "pro"
  envVars?: Record<string, string>
  buildCommand?: string
  startCommand?: string
  healthCheckPath?: string
  autoDeploy?: boolean
  branch?: string
  repoUrl?: string
}

export interface RenderDeploymentResult {
  success: boolean
  serviceId?: string
  serviceUrl?: string
  dashboardUrl?: string
  blueprintUrl?: string
  logs: string[]
  error?: string
}

// Render Regions
export const RENDER_REGIONS = [
  { id: "oregon", name: "Oregon, USA", code: "oregon" },
  { id: "frankfurt", name: "Frankfurt, Germany", code: "frankfurt" },
  { id: "singapore", name: "Singapore", code: "singapore" },
  { id: "ohio", name: "Ohio, USA", code: "ohio" },
]

// Render Plans
export const RENDER_PLANS = [
  { id: "free", name: "Free", price: "$0/mo", ram: "512MB", cpu: "Shared" },
  { id: "starter", name: "Starter", price: "$7/mo", ram: "512MB", cpu: "0.5 CPU" },
  { id: "standard", name: "Standard", price: "$25/mo", ram: "2GB", cpu: "1 CPU" },
  { id: "pro", name: "Pro", price: "$85/mo", ram: "4GB", cpu: "2 CPU" },
]

// Generate render.yaml Blueprint
export function generateRenderBlueprint(config: RenderDeploymentConfig): string {
  const {
    projectName,
    projectType,
    region,
    plan,
    envVars,
    buildCommand,
    startCommand,
    healthCheckPath,
    autoDeploy,
  } = config

  // Default commands based on project type
  const defaults: Record<string, { build: string; start: string }> = {
    nextjs: {
      build: "npm install && npm run build",
      start: "npm start",
    },
    node: {
      build: "npm install",
      start: "node index.js",
    },
    static: {
      build: "npm install && npm run build",
      start: "",
    },
    docker: {
      build: "",
      start: "",
    },
  }

  const actualBuildCommand = buildCommand || defaults[projectType]?.build || "npm install && npm run build"
  const actualStartCommand = startCommand || defaults[projectType]?.start || "npm start"

  // Build environment variables section
  let envVarsYaml = ""
  if (envVars && Object.keys(envVars).length > 0) {
    envVarsYaml = Object.entries(envVars)
      .map(([key, value]) => {
        if (value.startsWith("$")) {
          // Reference to another service or database
          return `      - key: ${key}\n        fromDatabase:\n          name: ${value.slice(1)}\n          property: connectionString`
        } else if (value === "GENERATE") {
          return `      - key: ${key}\n        generateValue: true`
        } else {
          return `      - key: ${key}\n        value: "${value}"`
        }
      })
      .join("\n")
  }

  // Generate blueprint based on project type
  if (projectType === "static") {
    return `# Render.com Blueprint - Generated by AgentForge
# Deploy: https://render.com/deploy?repo=YOUR_REPO_URL

services:
  - type: web
    name: ${projectName}
    runtime: static
    region: ${region}
    buildCommand: ${actualBuildCommand}
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
${envVarsYaml ? `    envVars:\n${envVarsYaml}` : ""}
    autoDeploy: ${autoDeploy !== false}
`
  }

  if (projectType === "docker") {
    return `# Render.com Blueprint - Generated by AgentForge
# Deploy: https://render.com/deploy?repo=YOUR_REPO_URL

services:
  - type: web
    name: ${projectName}
    runtime: docker
    region: ${region}
    plan: ${plan}
    dockerfilePath: ./Dockerfile
    dockerContext: .
${envVarsYaml ? `    envVars:\n${envVarsYaml}` : ""}
    autoDeploy: ${autoDeploy !== false}
${healthCheckPath ? `    healthCheckPath: ${healthCheckPath}` : ""}
`
  }

  // Default: Node.js / Next.js
  return `# Render.com Blueprint - Generated by AgentForge
# Deploy: https://render.com/deploy?repo=YOUR_REPO_URL

services:
  - type: web
    name: ${projectName}
    runtime: node
    region: ${region}
    plan: ${plan}
    buildCommand: ${actualBuildCommand}
    startCommand: ${actualStartCommand}
    envVars:
      - key: NODE_ENV
        value: production
${envVarsYaml ? envVarsYaml : ""}
    autoDeploy: ${autoDeploy !== false}
${healthCheckPath ? `    healthCheckPath: ${healthCheckPath}` : ""}
`
}

// Generate render.yaml with database
export function generateRenderBlueprintWithDB(config: RenderDeploymentConfig & {
  database?: {
    name: string
    type: "postgres" | "redis"
    plan: string
  }
}): string {
  let blueprint = generateRenderBlueprint(config)

  if (config.database) {
    const dbSection = config.database.type === "postgres"
      ? `
databases:
  - name: ${config.database.name}
    region: ${config.region}
    plan: ${config.database.plan || "free"}
    databaseName: ${config.projectName.replace(/-/g, "_")}_db
    user: ${config.projectName.replace(/-/g, "_")}_user
    ipAllowList: []
`
      : `
# Redis is configured via Render Dashboard
# Add Redis manually: Dashboard → New → Redis
`

    blueprint += dbSection
  }

  return blueprint
}

// Generate full project blueprint with multiple services
export function generateFullStackBlueprint(config: {
  projectName: string
  region: string
  includeDatabase?: boolean
  includeRedis?: boolean
  includeWorker?: boolean
}): string {
  const { projectName, region, includeDatabase, includeRedis, includeWorker } = config

  let blueprint = `# Render.com Blueprint - Full Stack Application
# Generated by AgentForge
# Deploy: https://render.com/deploy?repo=YOUR_REPO_URL

services:
  # Web Service (Next.js/Node.js)
  - type: web
    name: ${projectName}
    runtime: node
    region: ${region}
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
${includeDatabase ? `      - key: DATABASE_URL
        fromDatabase:
          name: ${projectName}-db
          property: connectionString` : ""}
${includeRedis ? `      - key: REDIS_URL
        fromService:
          type: redis
          name: ${projectName}-cache
          property: connectionString` : ""}
      - key: NEXTAUTH_SECRET
        generateValue: true
    autoDeploy: true
    healthCheckPath: /
`

  if (includeWorker) {
    blueprint += `
  # Background Worker
  - type: worker
    name: ${projectName}-worker
    runtime: node
    region: ${region}
    plan: free
    buildCommand: npm install
    startCommand: npm run worker
    envVars:
      - key: NODE_ENV
        value: production
${includeDatabase ? `      - key: DATABASE_URL
        fromDatabase:
          name: ${projectName}-db
          property: connectionString` : ""}
    autoDeploy: true
`
  }

  if (includeDatabase) {
    blueprint += `
databases:
  # PostgreSQL Database
  - name: ${projectName}-db
    region: ${region}
    plan: free
    databaseName: ${projectName.replace(/-/g, "_")}
    user: ${projectName.replace(/-/g, "_")}_user
    ipAllowList: []
`
  }

  if (includeRedis) {
    blueprint += `
# Note: Redis must be created manually in Render Dashboard
# Dashboard → New → Redis → Name: ${projectName}-cache
`
  }

  return blueprint
}

// Validate Render API Key format
export function validateRenderApiKey(apiKey: string): boolean {
  return apiKey.startsWith("rnd_") && apiKey.length > 20
}

// Deployment status types
export type RenderDeployStatus = "idle" | "creating" | "building" | "deploying" | "live" | "failed"

export interface RenderServiceInfo {
  id: string
  name: string
  type: string
  status: string
  url?: string
  createdAt: string
  updatedAt: string
}
